INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('1', '201', '0', '254');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('2', '83', '0', '189');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('3', '56', '0', '91');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('4', '63', '0', '152');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('5', '24', '0', '84');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('6', '79', '0', '183');
INSERT INTO `plypack`.`content` (`content_id`, `like_cnt`, `total_vote_cnt`, `view_cnt`) VALUES ('7', '88', '0', '161');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('1', '0', '2');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('2', '0', '2');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('3', '0', '2');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('4', '0', '2');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('5', '0', '2');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('1', '0', '3');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('2', '0', '3');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('3', '0', '3');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('4', '0', '3');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('5', '0', '3');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('1', '0', '4');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('2', '0', '4');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('3', '0', '4');
INSERT INTO `plypack`.`vote` (`choice`, `vote_cnt`, `content_id`) VALUES ('4', '0', '4');
